@startuml

title Buy USN

alice -> usn: send NEAR\n+ expected rate\n+ slippage\n+ transfer to

usn -> priceoracle: ""get_price_data""
activate priceoracle
usn <- priceoracle: NEAR/USDT rate
deactivate priceoracle
usn -> usn: verify timestamp

alt if expected rate and slippage is passed
usn -> usn: assert slippage
end

usn -> usn: mint USN

alice <-- usn: USN amount
alt If "transfer to" is defined
bob <-- usn: USN amount
end
@enduml
