@startuml

title Sell USN

alice -> usn: USN amount\n+ expected rate\n+ slippage

usn -> priceoracle: ""get_price_data""
activate priceoracle
usn <- priceoracle: NEAR/USDT rate
deactivate priceoracle
usn -> usn: verify timestamp

alt If expected rate and slippage is passed
usn -> usn: assert slippage
end

usn -> usn: burn USN
alice <-- usn: send NEAR
@enduml