name: Run tests

on:
  workflow_call:

  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Rustfmt
      run: cargo fmt -- --check
    - name: Run unit tests
      run: cargo test --verbose
    - name: Install NPM dependencies
      run: npm install
    - name: Build USN
      run: npm run build
    - name: Run integration tests on sandbox
      run: npm run test
